name: fuori_nevica
description: "App mobile per il progetto di sistemi distribuiti"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  device_info_plus: ^11.1.1
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
